name: "rzk-check"
description: "Typecheck an Rzk project"
branding:
  color: "purple"
  icon: "triangle"  # 2-simplex? :)
inputs:
  rzk-version:
    description: "Version of Rzk to use (latest by default)"
    required: false
    default: "latest"
  files:
    description: "Files to check (rely on rzk.yaml by default)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: 🔨 Install Rzk proof assistant
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: fizruk/rzk
        tag: ${{ inputs.rzk-version }}
        rename-to: rzk
        chmod: 0755

    - name: 🔨 Check Rzk files
      shell: bash
      run: |
        rzk typecheck ${{ inputs.files }}
