name: "rzk-check"
description: "Typecheck an Rzk project"
branding:
  color: "purple"
  icon: "triangle"  # 2-simplex? :)

inputs:
  system-rzk:
    description: "Use system rzk (instead of downloading binaries)"
    required: false
    default: false
  rzk-version:
    description: "Version of Rzk to use (latest by default)"
    required: false
    default: "latest"
  files:
    description: "Files to check (rely on rzk.yaml by default)"
    required: false
    default: ""

outputs:
  rzk-version:
    description: "Version of Rzk used"
    value: ${{ steps.check-rzk-version.outputs.rzk-version }}

runs:
  using: "composite"
  steps:
    - name: 🔨 Install Rzk proof assistant
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      if: ${{ inputs.system-rzk == 'false' }}
      with:
        repo: fizruk/rzk
        tag: ${{ inputs.rzk-version }}
        rename-to: rzk
        chmod: 0755

    - name: Check Rzk version
      shell: bash
      id: check-rzk-version
      run: |
        echo "rzk-version=$(rzk version)" >> $GITHUB_OUTPUT

    - name: 🔨 Check Rzk files
      shell: bash
      run: |
        rzk typecheck ${{ inputs.files }}
